<a href="https://colab.research.google.com/github/Pavankalyan2006/AD-/blob/master/TOY_STORY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
%matplotlib inline



In [ ]:
from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]

df = pd.read_csv(file_name)
df.head()

Saving Movie.csv to Movie.csv


userId             movie  rating
0       3  Toy Story (1995)     4.0
1       6  Toy Story (1995)     5.0
2       8  Toy Story (1995)     4.0
3      10  Toy Story (1995)     4.0
4      11  Toy Story (1995)     4.5

In [ ]:
df


userId             movie  rating
0          3  Toy Story (1995)     4.0
1          6  Toy Story (1995)     5.0
2          8  Toy Story (1995)     4.0
3         10  Toy Story (1995)     4.0
4         11  Toy Story (1995)     4.5
...      ...               ...     ...
8987    7087  GoldenEye (1995)     3.0
8988    7088  GoldenEye (1995)     1.0
8989    7105  GoldenEye (1995)     2.0
8990    7113  GoldenEye (1995)     3.0
8991    7117  GoldenEye (1995)     3.0

[8992 rows x 3 columns]

In [ ]:
len(df.movie.unique())

10

In [ ]:
df=df.dropna()

In [ ]:
df.pivot(index='userId',columns='movie',values='rating').reset_index(drop=True)

movie  Father of the Bride Part II (1995)  GoldenEye (1995)  \
0                                     NaN               NaN   
1                                     NaN               NaN   
2                                     NaN               NaN   
3                                     NaN               4.0   
4                                     NaN               NaN   
...                                   ...               ...   
4076                                  4.0               NaN   
4077                                  3.5               NaN   
4078                                  NaN               3.0   
4079                                  NaN               NaN   
4080                                  NaN               NaN   

movie  Grumpier Old Men (1995)  Heat (1995)  Jumanji (1995)  Sabrina (1995)  \
0                          NaN          NaN             3.5             NaN   
1                          4.0          NaN             NaN             NaN   
2                          NaN          NaN             NaN             NaN   
3                          NaN          3.0             NaN             NaN   
4                          NaN          NaN             3.0             NaN   
...                        ...          ...             ...             ...   
4076                       NaN          NaN             NaN             NaN   
4077                       NaN          NaN             NaN             NaN   
4078                       4.0          5.0             NaN             3.0   
4079                       NaN          NaN             NaN             NaN   
4080                       NaN          NaN             4.0             4.0   

movie  Sudden Death (1995)  Tom and Huck (1995)  Toy Story (1995)  \
0                      NaN                  NaN               NaN   
1                      NaN                  NaN               NaN   
2                      NaN                  NaN               4.0   
3                      NaN                  NaN               NaN   
4                      NaN                  NaN               NaN   
...                    ...                  ...               ...   
4076                   NaN                  NaN               NaN   
4077                   NaN                  NaN               4.0   
4078                   1.0                  NaN               4.0   
4079                   NaN                  NaN               5.0   
4080                   NaN                  NaN               4.5   

movie  Waiting to Exhale (1995)  
0                           NaN  
1                           NaN  
2                           NaN  
3                           NaN  
4                           NaN  
...                         ...  
4076                        NaN  
4077                        NaN  
4078                        NaN  
4079                        NaN  
4080                        NaN  

[4081 rows x 10 columns]

In [ ]:
df.fillna(0,inplace=True)


userId             movie  rating
0          3  Toy Story (1995)     4.0
1          6  Toy Story (1995)     5.0
2          8  Toy Story (1995)     4.0
3         10  Toy Story (1995)     4.0
4         11  Toy Story (1995)     4.5
...      ...               ...     ...
8987    7087  GoldenEye (1995)     3.0
8988    7088  GoldenEye (1995)     1.0
8989    7105  GoldenEye (1995)     2.0
8990    7113  GoldenEye (1995)     3.0
8991    7117  GoldenEye (1995)     3.0

[8992 rows x 3 columns]

In [ ]:
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine,correlation

In [ ]:
from scipy.spatial.distance import cosine,correlation
vec1=[5,4,3,0]
vec2=[4,5,3,0]
correlation(vec1,vec2)
print(correlation(vec1,vec2))


0.0714285714285714


In [ ]:
df.fillna(0, inplace=True)


In [ ]:
df_numeric = df.select_dtypes(include=[np.number])
user_sim = 1 - pairwise_distances(df_numeric.values, metric='cosine')
print(user_sim)

[[1.         0.97308029 0.89442719 ... 0.60022517 0.60033736 0.60033717]
 [0.97308029 1.         0.97341717 ... 0.76840146 0.76849122 0.76849107]
 [0.89442719 0.97341717 1.         ... 0.89455304 0.89461573 0.89461562]
 ...
 [0.60022517 0.76840146 0.89455304 ... 1.         0.99999999 0.99999999]
 [0.60033736 0.76849122 0.89461573 ... 0.99999999 1.         1.        ]
 [0.60033717 0.76849107 0.89461562 ... 0.99999999 1.         1.        ]]


In [ ]:
user_sim_df = pd.DataFrame(user_sim)
user_sim_df.head()

0         1         2         3         4         5         6     \
0  1.000000  0.973080  0.894427  0.854199  0.858234  0.822192  0.808736   
1  0.973080  1.000000  0.973417  0.951034  0.953420  0.931243  0.922519   
2  0.894427  0.973417  1.000000  0.996546  0.997164  0.989949  0.986394   
3  0.854199  0.951034  0.996546  1.000000  0.999969  0.998274  0.996639   
4  0.858234  0.953420  0.997164  0.999969  1.000000  0.997785  0.995969   

       7         8         9     ...      8982      8983      8984      8985  \
0  0.816024  0.737154  0.783839  ...  0.600453  0.600339  0.600452  0.600565   
1  0.927271  0.873042  0.905850  ...  0.768584  0.768493  0.768583  0.768673   
2  0.988372  0.961524  0.978791  ...  0.894680  0.894617  0.894680  0.894743   
3  0.997585  0.981017  0.992423  ...  0.928687  0.928634  0.928686  0.928739   
4  0.997012  0.979472  0.991432  ...  0.925761  0.925708  0.925761  0.925814   

       8986      8987      8988      8989      8990      8991  
0  0.600339  0.600339  0.600113  0.600225  0.600337  0.600337  
1  0.768492  0.768492  0.768312  0.768401  0.768491  0.768491  
2  0.894616  0.894616  0.894490  0.894553  0.894616  0.894616  
3  0.928634  0.928634  0.928529  0.928581  0.928633  0.928633  
4  0.925707  0.925707  0.925600  0.925654  0.925707  0.925706  

[5 rows x 8992 columns]

In [ ]:
user_sim_df.iloc[0:5, 0:5]

0         1         2         3         4
0  1.000000  0.973080  0.894427  0.854199  0.858234
1  0.973080  1.000000  0.973417  0.951034  0.953420
2  0.894427  0.973417  1.000000  0.996546  0.997164
3  0.854199  0.951034  0.996546  1.000000  0.999969
4  0.858234  0.953420  0.997164  0.999969  1.000000

In [ ]:
user_sim_df.idxmax(axis=1)

0          0
1          1
2          2
3          3
4          4
        ... 
8987    8987
8988    8988
8989    8989
8990    6462
8991    7162
Length: 8992, dtype: int64

In [ ]:
df[df["userId"]==6]

userId                    movie  rating
1          6         Toy Story (1995)     5.0
3725       6  Grumpier Old Men (1995)     3.0
6464       6           Sabrina (1995)     5.0

In [ ]:
df[df["userId"]==168]

userId             movie  rating
60     168  Toy Story (1995)     4.5

In [ ]:
df[df["userId"]==6] | df["userId"]==168 ]

TypeError: unsupported operand type(s) for |: 'float' and 'bool'